### ISSUE TITLE
JOSS paper ambiguous use of mathematical symbol for Mueller matrix and depolarizer

### ISSUE THREAD

**Issue by arendMoerman** [Jashcraf/katsu#32]
This issue is part of my JOSS review: https://github.com/openjournals/joss-reviews/issues/7375

In the paper, there is one mathematical equation describing the formalism of the Mueller matrix decomposition, where the full matrix $$M$$ is decomposed into a depolarizer, diattenuator, and retarder:
$$M=M M_\mathrm{R} M_\mathrm{D}.$$
As it is now, the symbol $$M$$ is used for both the total matrix and the depolarizer constituent of the decomposition, which is ambiguous. 

I believe this to be just a typo in the paper however, as in the [online documentation](https://katsu.readthedocs.io/en/latest/notebooks/PolarDecomposition.html) the symbol $$M_\Delta$$ is used for the depolarizer, which would break the ambiguity and resolve this issue.

Could you please fix this in the JOSS paper please?

**Comment by Jashcraf** [comment]
Thank you for the catch! I think it may be a compilation issue? The $M_{\Delta}$ is present in `paper.md`

https://github.com/Jashcraf/katsu/blob/e294475e7c70c3f8460712946965c2c374eb829e/paper.md?plain=1#L57

And shows up in the markdown preview
![image](https://github.com/user-attachments/assets/25970ec6-a738-4dc7-ae3b-5e228733da3f)

Looking at the Github action I found the source of the error
```
[INFO] [makePDF] LaTeX run number 1
Latexmk: ====Undefined refs and citations with line #s in .tex file:
Missing character: There is no 𝛥 (U+1D6E5) in font [NewCM10-Bold.otf]:mode=ba
Missing character: There is no 𝛥 (U+1D6E5) in font [NewCM10-Bold.otf]:mode=base;script=latn;language=dflt;!
Missing character: There is no 𝛥 (U+1D6E5) in font [NewCM10-Bold.otf]:mode=ba
Missing character: There is no 𝛥 (U+1D6E5) in font [NewCM10-Bold.otf]:mode=base;script=latn;language=dflt;!
Missing character: There is no 𝛥 (U+1D6E5) in font [NewCM10-Bold.otf]:mode=ba
Missing character: There is no 𝛥 (U+1D6E5) in font [NewCM10-Bold.otf]:mode=base;script=latn;language=dflt;!
Missing character: There is no 𝛥 (U+1D6E5) in font [NewCM10-Bold.otf]:mode=ba
```

It may not be present because the Delta is inside the `\mathbf{*}`, I'll move the Delta outside to see  if that fixes it.

**Comment by Jashcraf** [comment]
![image](https://github.com/user-attachments/assets/d3834bc6-7eac-4360-b98d-990b0754926c)

Looks like it worked!

**Comment by arendMoerman** [comment]
Great!
